config:
  가죽갑옷:
    Material_Name: LEATHER_CHESTPLATE
    name: '&a1'
    metadata: 0
    color: '3220D5'
    lore:
      - '&a- &f색상 닉네임을 &e노랑&f색으로 변경합니다.1'
      - '&7<우클릭시 닉네임의 색상이 적용됩니다.>'
      - '&4밑줄닉네임 사용 유저는 관리자에게 문의하세요.'
      - '&8<매니서버 10月 출석체크 이벤트>'
      - '&f'
      - '&e기간: &b2015년 11월 01일 - 06시 00분 이후'
      - '&b아이템의 사용이 불가능하며 일괄 삭제됩니다.'
      - '&f'
      - '&4[교환 불가]'
      - '&a- &fPLAYER님의 귀속 아이템 입니다.'